In [3]:
%run app.py

=== Тест CSV ===

=== Загрузка CSV с автоопределением типов ===
Имя	Возраст	Зарплата
Алиса	30	50000
Иван	25	45000
Тимур	35	60000
Денис	40	70000
Определенные типы столбцов: {'Имя': <class 'str'>, 'Возраст': <class 'int'>, 'Зарплата': <class 'int'>}

=== Тест Pickle ===

=== Загрузка Pickle с автоопределением типов ===
Имя	Возраст	Зарплата
Алиса	30	50000
Иван	25	45000
Тимур	35	60000
Денис	40	70000
Определенные типы столбцов: {'Имя': <class 'str'>, 'Возраст': <class 'int'>, 'Зарплата': <class 'int'>}

=== Тест Text ===
Таблица сохранена в текстовый файл: test_table.txt

=== Тест операций над таблицей ===

Строки с 1 по 3:
Имя	Возраст	Зарплата
Алиса	30	50000
Иван	25	45000
Тимур	35	60000

Строка, где Имя = 'Иван':
Имя	Возраст	Зарплата
Иван	25	45000

Типы столбцов:
{0: <class 'str'>, 1: <class 'int'>, 2: <class 'int'>}

Установка типов столбцов:
Имя	Возраст	Зарплата
Алиса	30	50000.0
Иван	25	45000.0
Тимур	35	60000.0
Денис	40	70000.0

Значения столбца 'Возраст':
[30, 25, 35, 40]

Обновляем значения в столбце 'Возраст':
Имя	Возраст	Зарплата
Алиса	31	50000.0
Иван	26	45000.0
Тимур	36	60000.0
Денис	41	70000.0

Получение одного значения из столбца 'Зарплата':
Значение: 50000.0

=== Тест concat ===
Имя	Возраст	Зарплата
Полина	30	50000
Марк	25	45000
Андрей	35	60000
Илья	40	70000

=== Тест split ===
Первая таблица:
Имя	Возраст	Зарплата
Алиса	31	50000.0
Иван	26	45000.0
Вторая таблица:
Имя	Возраст	Зарплата
Тимур	36	60000.0
Денис	41	70000.0